### ISSUE TITLE
I successfully entered the installation interface, but I don't recognize the internal hard drive

### ISSUE THREAD

**Issue by Yogoshiteyo** [mino389/opencore-0.7.4-big-sur-for-dell-7537-4210u-haswell#1]

**Comment by mino389** [comment]
change hard disk mode bios AHCI?

**Comment by Yogoshiteyo** [comment]
yes！

**Comment by Yogoshiteyo** [comment]
Using your latest uploaded OC, Monterey has been successfully installed, thank you very much, but also found some small problems, such as when using multiple fingers to operate the trackpad, the mouse pointer will drift to unexpected positions.
